import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/Header';
import Footer from '@/appComponents/footer/Footer';

const latoMono = Lato({
  variable: '--font-lato-mono',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Cosmic Security',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${latoMono.className} bg-background antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
