import type { Metadata } from 'next';
import { Heebo, Lato } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/Header';

const heeboSans = Heebo({
  variable: '--font-heebo-mono',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const latoMono = Lato({
  variable: '--font-lato-mono',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${heeboSans.variable} ${latoMono.variable} bg-background antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
